### ISSUE TITLE
Readme doesn't have info how to launch this program automatically

### ISSUE THREAD

**Issue by NooneAtAll** [rfjakob/earlyoom#144]
I'm noob and I was recommended this application

I used the `apt install` command here and I want it to be active automatically in the background  
But I want this program to launch automatically after computer was turned off

Of course I can (*and I have*) searched for ways to launch programs on startup  
But - as a noob - I'm utterly terrified whether I did it right or not

Since this application pops up casually in no-free-memory-slowdown discussions (for example, here [1](https://www.reddit.com/r/linux/comments/cmg48b/lets_talk_about_the_elephant_in_the_room_the/ew32t9y/), [2](https://www.reddit.com/r/linux/comments/cmg48b/lets_talk_about_the_elephant_in_the_room_the/ew3ecdx/), [3](https://askubuntu.com/questions/1180677/is-there-a-way-to-reserve-memory-for-os-to-keep-it-active-when-ram-usage-goes-to)), I suppose many noobs come here (like me) in hopes of "easy solution"

That's why, please, add at least some info about automatic launch into the readme

**Comment by hakavlad** [comment]
@NooneAtAll `earlyoom` starts automatically when installed by the methods suggested in the README.

**Comment by NooneAtAll** [comment]
the only mention of automatic start is in manual compiling  
> Start earlyoom automatically by registering it as a service:

But it doesn't mention whether it does that for `apt install` method

I know that you answered me here, but people reading only readme might not see it

**Comment by birdie-github** [comment]
You should really ask on your distro forums.

In general, even if you're not sure whether it starts automatically or not you could run:

`sudo systemctl enable earlyoom` and
`sudo systemctl start earlyoom` to start it right away.

**Comment by Mikaela** [comment]
> In general, even if you're not sure whether it starts automatically or not you could run:

This only applies if the distribution is using systemd and I would instead say `systemctl status earlyoom` which on the first line will say: `Loaded: loaded (/lib/systemd/system/earlyoom.service; enabled; vendor preset: disabled)`

the enabled means that it's going to start on boot `vendor preset: disabled` that it would not start automatically on boot unless it was enabled.

and on the second line `Active: active (running) since Sun 2020-01-05 12:56:22 EET; 1h 54min ago`

More universal method to see whether it's currently running would be `ps aux | grep earlyoom` which for me gives `root       842  0.0  0.0   2300  1912 ?        SLs  12:56   0:00 /usr/bin/earlyoom -r 60`

> `sudo systemctl enable earlyoom` and
> `sudo systemctl start earlyoom` to start it right away.

These can be merged to `sudo systemctl enable --now earlyoom`

**Comment by hakavlad** [comment]
>These can be merged to sudo systemctl enable --now earlyoom

This may not work with older versions of systems. For example, this does not work on Debian 9.
