### ISSUE TITLE
Improve log message: add user id of killed job

### ISSUE THREAD

**Issue by lumbric** [rfjakob/earlyoom#151]
I'd suggest to add the uid/user name of the killed job to the log message. This might not be important for Desktop computers, but it is a very important information when used on multi user systems.

Maybe also include other helpful information like command line arguments or so? Parent process?
(The point is, the moment somebody is reading the log file, the process is already dead and it might be important to find out what has been killed.)

oom writes to log something like this:
```
Dec 12 09:04:44 mycomputer kernel: [2401186.209044] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice,task=python,pid=48845,uid=1003
```

earlyoom writes:
```
sending SIGTERM to process 73540 "python3": badness 460, VmRSS 29578 MiB
```

As far as I can see, only `/proc/*/status` contains the uid, but this is the human readable file if I understand correctly. So I'm not completely sure what is the right place to get this information from.

**Comment by hakavlad** [comment]
An example of good output:

```
Found 99 living tasks
Process with highest badness (found in 12 ms):
  PID: 23910, Name: tail, badness: 697
Victim state (found in 1 ms):
  Name:      tail
  State:     R (running)
  PID:       23910
  Ancestry:  PID 23904 (bash) <= PID 23874 (lxterminal) <= PID 1977 (mate-panel)
  EUID:      1000
  badness:   697, oom_score:  697, oom_score_adj:  0
  VmSize:    20449 MiB
  VmRSS:      7085 MiB  (Anon: 7083 MiB, File: 1 MiB, Shmem: 0 MiB)
  VmSwap:    13360 MiB
  CGroup_v1: 
  CGroup_v2: /user.slice/user-1000.slice/session-2.scope
  NSsid:     23904 (bash)
  Realpath:  /usr/bin/tail
  Cwd:       /home/user
  Lifetime:  20 sec
Implement a corrective action:
  Send SIGTERM to the victim; total response time: 14 ms
The victim died in 1.295 sec
Memory status after implementing a corrective action:
  MemAvailable: 7147.8 MiB, SwapFree: 15071.0 MiB
```

**Comment by hakavlad** [comment]
@rfjakob What about adding an option to enable printing of the state of processes before applying a corrective action, as in option `-d`? Users will be able to see the names and memory status of other processes, not just the victims.

**Comment by danielluke** [comment]
I'd like to see the contents of /proc/pid/cmdline in the log.

In my use, I've got a process manager that has many children - earlyoom works perfectly to kill the children using too much memory, but the log just contains /proc/pid/comm and so I only see the name of the process manager and not the child that was killed.

**Comment by rfjakob** [comment]
Including the uid is a good idea. Looking at `man proc`, it really looks like we have to parse `/proc/[pid]/status`. The file format seems to be the same as `/proc/meminfo`, so you could reuse at least `get_entry` from [meminfo.c](https://github.com/rfjakob/earlyoom/blob/master/meminfo.c). You can also look at `parse_meminfo()` for inspiration.

**Comment by lumbric** [comment]
How about using ownership of `/proc/[pid]`? I got stuck, when trying to
research the difference to `/proc/[pid]/status`.

>

**Comment by rfjakob** [comment]
Good idea, but risky, as the meaning of the ower of /proc/[pid] does not seem to be documented. Also, looks like it can change to root when a process makes itself "undumpable": https://stackoverflow.com/a/55345948/1380267

**Comment by hakavlad** [comment]
What is owner of  `/proc/[pid]`?

**Comment by hakavlad** [comment]
>Improve log message: add user id

Real UID, Effective UID, Login UID? What do you suggest?

**Comment by hakavlad** [comment]
> ower of /proc/[pid] does not seem to be documented

This is well documented. `man proc`.

Real, effective, saved set, and file system UIDs (GIDs)
https://en.wikipedia.org/wiki/User_identifier

**Comment by rfjakob** [comment]
> What is owner of /proc/[pid]?

Yes, that's the problem, we don't know.

> Real UID, Effective UID, Login UID?

I *think* real uid is the right choice here, but we should use the same thing that `ps auxn` uses for its USER column.

**Comment by hakavlad** [comment]
I suggest RUID or EUID.

**Comment by rfjakob** [comment]
> This is well documented. man proc.

Can you copy-paste what you found? I did not find it.

**Comment by hakavlad** [comment]
>Uid, Gid: Real, effective, saved set, and file system UIDs (GIDs). 

https://linux.die.net/man/5/proc

What does it mean? - https://en.wikipedia.org/wiki/User_identifier

**Effective user ID**

The effective UID (euid) of a process is used for most access checks. It is also used as the owner for files created by that process. The effective GID (egid) of a process also affects access control and may also affect file creation, depending on the semantics of the specific kernel implementation in use and possibly the mount options used. According to BSD Unix semantics, the group ownership given to a newly created file is unconditionally inherited from the group ownership of the directory in which it is created. According to AT&T UNIX System V semantics (also adopted by Linux variants), a newly created file is normally given the group ownership specified by the egid of the process that creates the file. Most filesystems implement a method to select whether BSD or AT&T semantics should be used regarding group ownership of a newly created file; BSD semantics are selected for specific directories when the S_ISGID (s-gid) permission is set.[1]
**File system user ID**

Linux also has a file system user ID (fsuid) which is used explicitly for access control to the file system. It matches the euid unless explicitly set otherwise. It may be root's user ID only if ruid, suid, or euid is root. Whenever the euid is changed, the change is propagated to the fsuid.

The intent of fsuid is to permit programs (e.g., the NFS server) to limit themselves to the file system rights of some given uid without giving that uid permission to send them signals. Since kernel 2.0, the existence of fsuid is no longer necessary because Linux adheres to SUSv3 rules for sending signals, but fsuid remains for compatibility reasons.[2]
**Saved user ID**

The saved user ID (suid) is used when a program running with elevated privileges needs to do some unprivileged work temporarily; changing euid from a privileged value (typically 0) to some unprivileged value (anything other than the privileged value) causes the privileged value to be stored in suid.[3] Later, a program's euid can be set back to the value stored in suid, so that elevated privileges can be restored; an unprivileged process may set its euid to one of only three values: the value of ruid, the value of suid, or the value of euid.
**Real user ID**
The real UID (ruid) and real GID (rgid) identify the real owner of the process and affect the permissions for sending signals. A process without superuser privileges may signal another process only if the sender's ruid or euid matches receiver's ruid or suid. Because a child process inherits its credentials from its parent, a child and parent may signal each other.

**Comment by hakavlad** [comment]
$ cat /proc/self/status
Name:	cat
Umask:	0022
State:	R (running)
Tgid:	7985
Ngid:	0
Pid:	7985
PPid:	7978
TracerPid:	0
**Uid:	1000	1000	1000	1000**
-- Real, effective, saved set, and file system UIDs

**Comment by rfjakob** [comment]
Yes, but the question was about the owner of /proc/[pid].

**Comment by hakavlad** [comment]
Real user ID
The real UID (ruid) and real GID (rgid) identify the **real owner**

**Comment by rfjakob** [comment]
I known what the RUID is, thanks, but the question is what the owner of /proc/[pid] means, and where this is documented.

**Comment by hakavlad** [comment]
There is no single ownership. There are *real owner of the process and affect the permissions for sending signals* and *process also affects access control and may also affect file creation*.

**Comment by rfjakob** [comment]
Yes there is a single ownership of the /proc/[pid] directory.

**Comment by hakavlad** [comment]
>Yes there is a single ownership of the /proc/[pid] directory.

owner of any /proc/pid is root.

**Comment by rfjakob** [comment]
No.
```
/proc$ ls -l
total 0
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:02 1
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:02 10
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:03 1008
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:03 1011
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:03 1020
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:03 1022
dr-xr-xr-x.  9 root    root                  0 Jan  8 18:03 1023
dr-xr-xr-x.  9 colord  colord                0 Jan  8 18:03 1032
dr-xr-xr-x.  9 jakob   jakob                 0 Jan  8 18:03 1045
dr-xr-xr-x.  9 jakob   jakob                 0 Jan 19 14:30 104646
dr-xr-xr-x.  9 jakob   jakob                 0 Jan 19 14:30 104647
dr-xr-xr-x.  9 jakob   jakob                 0 Jan  8 18:03 1057
```

**Comment by hakavlad** [comment]
I think this should be euid

>The effective UID (euid) of a process is used for most access checks. It is also used as the owner for files created by that process. The effective GID (egid) of a process also affects access control and may also affect file creation

**Comment by rfjakob** [comment]
> I think this should be euid

In other words, we don't know, and it's not documented.

@lumbric please use /proc/[pid]/status , which is documented.

**Comment by hakavlad** [comment]
euid used to determinate files access control. It is documented.

**Comment by rfjakob** [comment]
...and does that mean /proc/[pid] will be owned by euid? Yes? No? Maybe? 

No, not good enough for me. I don't want to build earlyoom on maybe.

**Comment by hakavlad** [comment]
In fact, it does not matter who the owner is. It is important that the behavior matches the documentation. You can choose any parameter - EID or RUID and indicate this in the documentation - which particular UID is meant.

**Comment by hakavlad** [comment]
>Yes? No? Maybe?

Print "eUID: 1000" in log instaed of "UID: 1000", and uncertainty will disappear.
