### ISSUE TITLE
Kill the process that triggers OOM while applying for memory instead of highest oom_score

### ISSUE THREAD

**Issue by zhenLiuXplr** [rfjakob/earlyoom#265]
Hi

I install earlyoom on server and it runs really well. But recently I meet a problem that sometime I want to kill the process that triggers OOM while applying for memory instead of killing the process with highest oom_score. Maybe like what OOM designed when oom_kill_allocating_task not 0.

It is because usually on a server, some large programs runing for a very long time, but when more processes load to the server, the large program might be killed and waste the runing time it has used.

Really hope you can give some suggestion.
Thanks!

**Comment by hakavlad** [comment]
I don't see a way to easily implement this. 

Workaround: just protect important processes using `--avoid` option.

**Comment by zhenLiuXplr** [comment]
Thanks. I'm going to close this issue. If you find any solution in the future, please reopen this issue.

**Comment by mikkorantalainen** [comment]
I think this should not be implemented and using the kernel config `oom_kill_allocating_task` is dangerous to use, too. The problem with always killing the allocating task is that it will kill practically random process because if e.g. some background shell script (e.g. cron job) needs to acquire 4 KB more memory for stack it will be killed instead of some big process eating lots of RAM and causing the problem.

If you want the allocating process to be punished, you should set `/sys/proc/vm/overcommit_memory` to `2` instead. That will allow well written processes to correctly handle out of RAM situation and if the process fails to notice that `malloc()` returned zero, it will be killed with SIGSEGV when it tries to use the pointer. For details, see https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

In real world, with less than perfectly programmed applications, configuring all important processes as not-a-target for killing and enabling unlimited overcommit seems to work better for most cases. The standard method for specifying correct target for killing is to write suitable value to `/proc/<pid>/oom_score_adj`.
