### ISSUE TITLE
Makefile getting version only works when checking out from git repo.

### ISSUE THREAD

**Issue by papamoose** [rfjakob/earlyoom#28]
I was hoping someone could fix this line in the make file such that it works if you download a release: `VERSION ?= $(shell git describe --tags --dirty)`

The following shell code might be a good starting point, but since I don't know make I'm not sure if it is appropriate.
`git describe --tags --dirty 2> /dev/null || basename $PWD | sed 's/earlyoom-//'`

This assumes you have downloaded a release like so

    VERSION=0.11
    wget -q https://github.com/rfjakob/earlyoom/archive/v${VERSION}.tar.gz
    tar -xzf v${VERSION}.tar.gz
    cd earlyoom-${VERSION}

As you can see the version is included in the filename so I propose using the file name as the basis for this. Though, I could see having a VERSION file would be much simpler.

Feel free to ignore me and just delete this issue (serious).

**Comment by rfjakob** [comment]
It's somewhat better as of https://github.com/rfjakob/earlyoom/commit/46bed73b37cce65462bfc81e4b60e78e70c5ea1a as you'll get "unknown version" and no git error message:

```
$ make
cc -Wall -Wextra -DVERSION=\""(unknown version)"\" -g -o earlyoom meminfo.c kill.c main.c
$ ./earlyoom -v
earlyoom (unknown version)
```

Also, since https://github.com/rfjakob/earlyoom/commit/0cf92680e5a570e84de9ab40634a94b629eddb5e you can build with a manual version like this:

```
VERSION=123 make
```

I think we are in pretty good shape now!
