### ISSUE TITLE
/etc/earlyoom.conf instead of /etc/default/earlyoom

### ISSUE THREAD

**Issue by hakavlad** [rfjakob/earlyoom#75]
earlyoom.conf may be looking like follow:

```
# This is earlyoom config file

# comment
mem_min_sigkill = 6 %

# comment
swap_min_sigkill = 200 M

# for chromium, comment how it works
decrease_oom_score_adj = False

# comment, how it works
desktop_notifications = False

# comment, examples
prefer = 

# comment
avoid = ssh|Xorg

# comment
self_nice = 0

# comment
self_oom_score_adj = 0

# comment
debug = False
```
Advantages is it more convenient for users, IMHO.
Users may easy find all defaults and what means each parameter.

What is disadvantages?

**Comment by rfjakob** [comment]
One disadvantage is that it introduces a depency on some ini parser lib. There is nothing built into c stdlib.

**Comment by rfjakob** [comment]
But fundamentally i don't like the extra complexity.
I'd like to keep earlyoom simple and stupid and work "well enough" for most (all?) cases without any configuration, even if that means it does not work "perfectly" in all cases.

Maybe this is where nohang fits in? If you need more flexibility, you use it instead of earlyoom? I believe having the more complex features in python instead of c is a good idea anyway (I fixed a shell injection vulnerability yesterday)

**Comment by ForumPlayer** [comment]
> One disadvantage is that it introduces a depency on some ini parser lib. There is nothing built into c stdlib.

Not exactly, you could parse it as _"environment vars"_; or even use additional vars for each option, like this:
```
EARLYOOM_REPORT=3600
EARLYOOM_MIN_RAM=15
EARLYOOM_MIN_SWAP=5
EARLYOOM_AVOID='(^|/)(init|systemd|Xorg|sshd)$'
EARLYOOM_PREFER='(^|/)(chrome_crashpad_handler)$'
```
So you parse it the same way you already parse the `EARLYOOM_ARGS` var.
